# Issue ops
name: issue-ops

on:
  issues:
    types: [labeled]

jobs:
    issue-ops:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            contents: read
        steps:
        - name: Issue Forms Body Parser
          id: parse
          uses: zentered/issue-forms-body-parser@v2.0.0

        - uses: actions/checkout@v4.1.1
        - run: |

            repo_name=$(echo '${{ steps.parse.outputs.data }}' | jq -r '.name.text')
            repo_dept=$(echo '${{ steps.parse.outputs.data }}' | jq -r '.department.text')

            echo "Name $repo_name"
            echo "Dept $repo_dept"

            # gh issue comment ${{ github.event.issue.number }} -b "Request: ${{ github.event.issue.title }}" 
          env:
            GH_TOKEN: ${{ github.token }}
