 name: Self-Hosted

on: [workflow_dispatch]

jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Output environment
        shell: bash
        run: |-
          echo "Kernel: $(uname -S) $(uname -r)"
          echo "Machine: $(uname -m) $(uname -r)"
          echo "Runner Name: '${{ runner.name }}'"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner ARCH: ${{ runner.arch }}"
          
        
